packageExtensions:
  # Fix strapi yarn dependencies
  # "@strapi/admin@4.0.1":
  #   dependencies:
  #     "@strapi/strapi": "4.0.1"
  #     "object-assign": "*"
  #     "whatwg-fetch": "*"
  #     "react-is": "*"
  # "@strapi/strapi@4.0.1":
  #   dependencies:
  #     "@strapi/plugin-documentation": "4.0.1"
  #     "@strapi/plugin-graphql": "4.0.1"
  #     "@strapi/plugin-i18n": "4.0.1"
  #     "@strapi/plugin-users-permissions": "4.0.1"
  #     "sqlite3": "5.x.x"
  #     "graphql": "16.x.x"
  #     "resolve-cwd": "*"
  # "@strapi/database@4.0.1":
  #   dependencies:
  #     "sqlite3": "5.x.x"
  # "@strapi/babel-plugin-switch-ee-ce@4.0.1":
  #   dependencies:
  #     "@babel/template": "*"
  #     "reselect": "*"
  #     "resolve": "*"
  # "@strapi/plugin-content-type-builder@4.0.1":
  #   dependencies:
  #     "@strapi/helper-plugin": "4.0.1"
  #     "@babel/runtime": "*"
  #     "@strapi/icons": "latest"
  #     "@strapi/design-system": "latest"
  #     "prop-types": "*"
  # "@strapi/plugin-email@4.0.1":
  #   dependencies:
  #     "@strapi/helper-plugin": "4.0.1"
  #     "@babel/runtime": "*"
  #     "@strapi/icons": "latest"
  #     "@strapi/design-system": "latest"
  #     "prop-types": "*"
  # "@strapi/plugin-graphql@4.0.1":
  #   dependencies:
  #     "@strapi/helper-plugin": "4.0.1"
  #     "@babel/runtime": "*"
  #     "@strapi/icons": "latest"
  #     "@strapi/design-system": "latest"
  #     "prop-types": "*"
  # "@strapi/plugin-i18n@4.0.1":
  #   dependencies:
  #     "@strapi/helper-plugin": "4.0.1"
  #     "@babel/runtime": "*"
  #     "@strapi/icons": "latest"
  #     "@strapi/design-system": "latest"
  #     "prop-types": "*"
  #     "axios": "*"
  # "@strapi/plugin-upload@4.0.1":
  #   dependencies:
  #     "@strapi/helper-plugin": "4.0.1"
  #     "@babel/runtime": "*"
  #     "@strapi/icons": "latest"
  #     "@strapi/design-system": "latest"
  #     "prop-types": "*"
  #     "axios": "*"
  #     "console-browserify": "*"
  # "@strapi/plugin-documentation@4.0.1":
  #   dependencies:
  #     "@strapi/helper-plugin": "4.0.1"
  #     "@babel/runtime": "*"
  #     "@strapi/icons": "latest"
  #     "@strapi/design-system": "latest"
  #     "formik": "*"
  #     "prop-types": "*"
  # "@strapi/plugin-users-permissions@4.0.1":
  #   dependencies:
  #     "@strapi/helper-plugin": "4.0.1"
  #     "@babel/runtime": "*"
  #     "@strapi/icons": "latest"
  #     "@strapi/design-system": "latest"
  #     "react-query": "*"
  #     "formik": "*"
  #     "prop-types": "*"
  #     "@fortawesome/react-fontawesome": "*"
  # "console-browserify@*":
  #   dependencies:
  #     "util": "*"
  #     "assert": "*"
  # "util@*":
  #   dependencies:
  #     "console-browserify": "*"
  #     "process": "*"
  # "assert@*":
  #   dependencies:
  #     "console-browserify": "*"
  #     "process": "*"
  # "react-dom@*":
  #   dependencies:
  #     "console-browserify": "*"
  # "react-helmet@*":
  #   dependencies:
  #     "console-browserify": "*"
  # "redux@*":
  #   dependencies:
  #     "console-browserify": "*"
  # "scheduler@*":
  #   dependencies:
  #     "console-browserify": "*"
  # "tiny-warning@1.x.x":
  #   dependencies:
  #     "console-browserify": "*"
  # "react-fast-compare@3.x.x":
  #   dependencies:
  #     "console-browserify": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
