packageExtensions:
  "@strapi/admin@4.0.0":
    dependencies:
      "@strapi/strapi": "4.0.0"
  "@strapi/strapi@4.0.0":
    dependencies:
      "@strapi/plugin-documentation": "4.0.0"
      "@strapi/plugin-graphql": "4.0.0"
      "@strapi/plugin-i18n": "4.0.0"
      "@strapi/plugin-users-permissions": "4.0.0"
      "sqlite3": "5.x.x"
      "graphql": "16.x.x"
  "@strapi/database@4.0.0":
    dependencies:
      "sqlite3": "5.x.x"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
